title: TinyML Swarm Research
description: My 12-month path to expand my knowledge of distributed machine learning
author: sharris416
email: steve@employinginnovation.com
url: "https://sharris416.github.io"

# Theme
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
